# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b908137da2b92b632ec6a102dda2414cfec738eff73834f060452c401ed2b8e33d023ef3de60cbfc39efcb56b415f03259cb6d60417f00128c5772a8c083460

test:
  secret_key_base: 3748614e06589d12e97dd6fbfb2ca9b515356f307b9bf3a45f8eee7c03789231ed1e86f891db65474bcca284aa2cdec123c285012b434d10d9e7d87a72447498

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
